# Generated by Django 2.1 on 2019-04-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='contents',
            new_name='content',
        ),
    ]
