# Generated by Django 2.1 on 2019-04-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20190430_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='content',
            new_name='contents',
        ),
    ]
